CREATE TABLE IF NOT EXISTS tickets (
  id VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  price MONEY NOT NULL DEFAULT 0,
  image VARCHAR(100) NOT NULL,
  amount SMALLINT NOT NULL DEFAULT 0,
  user_id VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id),
  FOREIGN KEY(user_id) REFERENCES users(id)
);
