// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"tiketo/entity"

	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepositoryInterface type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Create(context1 context.Context, dB *gorm.DB, user *entity.User) error {
	ret := _mock.Called(context1, dB, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.User) error); ok {
		r0 = returnFunc(context1, dB, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - dB *gorm.DB
//   - user *entity.User
func (_e *MockUserRepository_Expecter) Create(context1 interface{}, dB interface{}, user interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", context1, dB, user)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(context1 context.Context, dB *gorm.DB, user *entity.User)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		var arg2 *entity.User
		if args[2] != nil {
			arg2 = args[2].(*entity.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(err error) *MockUserRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(context1 context.Context, dB *gorm.DB, user *entity.User) error) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Delete(context1 context.Context, dB *gorm.DB, user *entity.User) error {
	ret := _mock.Called(context1, dB, user)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.User) error); ok {
		r0 = returnFunc(context1, dB, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - dB *gorm.DB
//   - user *entity.User
func (_e *MockUserRepository_Expecter) Delete(context1 interface{}, dB interface{}, user interface{}) *MockUserRepository_Delete_Call {
	return &MockUserRepository_Delete_Call{Call: _e.mock.On("Delete", context1, dB, user)}
}

func (_c *MockUserRepository_Delete_Call) Run(run func(context1 context.Context, dB *gorm.DB, user *entity.User)) *MockUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		var arg2 *entity.User
		if args[2] != nil {
			arg2 = args[2].(*entity.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_Delete_Call) Return(err error) *MockUserRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Delete_Call) RunAndReturn(run func(context1 context.Context, dB *gorm.DB, user *entity.User) error) *MockUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Save(context1 context.Context, dB *gorm.DB, user *entity.User) error {
	ret := _mock.Called(context1, dB, user)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.User) error); ok {
		r0 = returnFunc(context1, dB, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - dB *gorm.DB
//   - user *entity.User
func (_e *MockUserRepository_Expecter) Save(context1 interface{}, dB interface{}, user interface{}) *MockUserRepository_Save_Call {
	return &MockUserRepository_Save_Call{Call: _e.mock.On("Save", context1, dB, user)}
}

func (_c *MockUserRepository_Save_Call) Run(run func(context1 context.Context, dB *gorm.DB, user *entity.User)) *MockUserRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		var arg2 *entity.User
		if args[2] != nil {
			arg2 = args[2].(*entity.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_Save_Call) Return(err error) *MockUserRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Save_Call) RunAndReturn(run func(context1 context.Context, dB *gorm.DB, user *entity.User) error) *MockUserRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Take provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Take(context1 context.Context, dB *gorm.DB, user *entity.User) error {
	ret := _mock.Called(context1, dB, user)

	if len(ret) == 0 {
		panic("no return value specified for Take")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.User) error); ok {
		r0 = returnFunc(context1, dB, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Take_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Take'
type MockUserRepository_Take_Call struct {
	*mock.Call
}

// Take is a helper method to define mock.On call
//   - context1 context.Context
//   - dB *gorm.DB
//   - user *entity.User
func (_e *MockUserRepository_Expecter) Take(context1 interface{}, dB interface{}, user interface{}) *MockUserRepository_Take_Call {
	return &MockUserRepository_Take_Call{Call: _e.mock.On("Take", context1, dB, user)}
}

func (_c *MockUserRepository_Take_Call) Run(run func(context1 context.Context, dB *gorm.DB, user *entity.User)) *MockUserRepository_Take_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		var arg2 *entity.User
		if args[2] != nil {
			arg2 = args[2].(*entity.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_Take_Call) Return(err error) *MockUserRepository_Take_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Take_Call) RunAndReturn(run func(context1 context.Context, dB *gorm.DB, user *entity.User) error) *MockUserRepository_Take_Call {
	_c.Call.Return(run)
	return _c
}

// TakeForUpdate provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) TakeForUpdate(context1 context.Context, dB *gorm.DB, user *entity.User) error {
	ret := _mock.Called(context1, dB, user)

	if len(ret) == 0 {
		panic("no return value specified for TakeForUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.User) error); ok {
		r0 = returnFunc(context1, dB, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_TakeForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TakeForUpdate'
type MockUserRepository_TakeForUpdate_Call struct {
	*mock.Call
}

// TakeForUpdate is a helper method to define mock.On call
//   - context1 context.Context
//   - dB *gorm.DB
//   - user *entity.User
func (_e *MockUserRepository_Expecter) TakeForUpdate(context1 interface{}, dB interface{}, user interface{}) *MockUserRepository_TakeForUpdate_Call {
	return &MockUserRepository_TakeForUpdate_Call{Call: _e.mock.On("TakeForUpdate", context1, dB, user)}
}

func (_c *MockUserRepository_TakeForUpdate_Call) Run(run func(context1 context.Context, dB *gorm.DB, user *entity.User)) *MockUserRepository_TakeForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		var arg2 *entity.User
		if args[2] != nil {
			arg2 = args[2].(*entity.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_TakeForUpdate_Call) Return(err error) *MockUserRepository_TakeForUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_TakeForUpdate_Call) RunAndReturn(run func(context1 context.Context, dB *gorm.DB, user *entity.User) error) *MockUserRepository_TakeForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Update(context1 context.Context, dB *gorm.DB, user *entity.User) error {
	ret := _mock.Called(context1, dB, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gorm.DB, *entity.User) error); ok {
		r0 = returnFunc(context1, dB, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - dB *gorm.DB
//   - user *entity.User
func (_e *MockUserRepository_Expecter) Update(context1 interface{}, dB interface{}, user interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", context1, dB, user)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(context1 context.Context, dB *gorm.DB, user *entity.User)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *gorm.DB
		if args[1] != nil {
			arg1 = args[1].(*gorm.DB)
		}
		var arg2 *entity.User
		if args[2] != nil {
			arg2 = args[2].(*entity.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(err error) *MockUserRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(context1 context.Context, dB *gorm.DB, user *entity.User) error) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
